---
- name: Setup Dev Box
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Import Microsoft GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add VS Code repo
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      notify: refresh dnf cache

    - name: Add HashiCorp DNF/YUM Repository
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
        owner: root
        group: root
        mode: '0644'

    - name: Install required packages
      package:
        name:
          - btop
          - code
          - moby-engine
          - dotnet-sdk-9.0
          - git 
          - golang
          - htop
          - neovim
          - terraform          
        state: present

  handlers:
    - name: refresh dnf cache
      command: dnf makecache

